Lambdaはエラーが発生すると、JSON を返す
▼ 下記でエラー発生
-------------------------------------------------
def always_failed_handler(event, context):
    raise Exception('I failed!')

-------------------------------------------------
▼ 返り値
-------------------------------------------------
{
  "errorMessage": "I failed!",
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      3,
      "my_always_fails_handler",
      "raise Exception('I failed!')"
      ]
        ],
        "errorType": "Exception"
      }
-------------------------------------------------


▼ エラー時のリトライ
-------------------------------------------------
・イベントソースによっては、失敗したLambdaをリトライする
・Kinesis
 →成功するか、レコードストリームが失効するまでリトライ  


-------------------------------------------------
