# 例外処理基本

* 例外処理を行わないと、エラー発生時にプログラムが止まる



# プログラムに、エラーを検知させよ！で、適切に処理してクラッシュを回避するのです



* 例外処理を行えば、エラー発生時に except に処理が移るが、その後通常通りの処理が進む





# 下記だと、エラーが発生する


```py

def spam(divideBy):
    return 42 / divideBy

print(spam(2))
print(spam(12))
print(spam(0))
print(spam(1))
```


# 出力

```py
Traceback (most recent call last):
File "C:/zeroDivide.py", line 6, in <module> print(spam(0))
File "C:/zeroDivide.py", line 2, in spam return 42 / divideBy
             ZeroDivisionError: division by zero
```




# 例外処理らしい処理

```py
def spam(divideBy):
    try:
        return 42 / divideBy
    except ZeroDivisionError:
      print('Error: Invalid argument.')


print(spam(2))
print(spam(12))
print(spam(0))
print(spam(1))
```



# 出力

```py
21.0
3.5
Error: Invalid argument. None
42.0
```
